todo_files/urls.py
from django.urls import path
from todo.views import TodoDetailView, TodoListView, NoteDetailView, NoteListView





urlpatterns = [
    path('', TodoListView.as_view(), name='todo_list'),
    path('<int:task_id>', TodoDetailView.as_view(), name='task'),
    path('notes', NoteListView.as_view(), name='note'),
    # path('<int:note_id>', NoteDetailView.as_view(), name='note'),
]

todo_files/models.py
# from datetime import datetime
from django.db import models

# Create your models here.

class Tag(models.Model):
    name = models.CharField(max_length=255)
class Task(models.Model):
    # An ID field is automatically added to all Django models
    description = models.CharField(max_length=255)
    completed = models.BooleanField(default=False)
    tags = models.ManyToManyField(Tag)

    # class Meta:
    #    ordering = ['-id']

class Note(models.Model):
    text = models.CharField(max_length=255)
    # created = models.DateTimeField(auto_now_add=True)

    # def __str__(self):
    #     return self.text

todo_files/forms.py
from django import forms

class TaskForm(forms.Form):
    description = forms.CharField(label='Add task', max_length=255)
#    complete = forms.CharField(label='Add task', max_length=255) 
class NoteForm(forms.Form):
    description = forms.CharField(label='Add note', max_length=255)

todo_files/views.py
# from urllib.request import Request
# from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.views import View

from todo.models import Task, Tag, Note
from todo.forms import TaskForm, NoteForm

# def index(request):
#     return HttpResponse('Hello world')
class TodoListView(View):
    def get(self, request):
        '''GET the todo list homepage, listing all tasks in reverse order that they were created'''
        tasks = Task.objects.all.order_by('-id')               
        completed_tasks = Task.objects.filter(completed=True).order_by('-id')
        # notes = Note.objects.all().order_by('-id')
        form = TaskForm()
        # form2 = NoteForm()

        return render(
            request = request, template_name = 'list.html', context = {'tasks': tasks, 'completed_tasks': completed_tasks,'form': form,}
        )

    def post(self, request):
        '''POST the data in the from submitted by the user, creating a new task in the todo list'''
        form=TaskForm(request.POST)
        if form.is_valid():
            task_description = form.cleaned_data['description']
            Task.objects.create(description=task_description)
            #"redirect" to the todo homepage
        return redirect('todo_list')


class TodoDetailView(View):
    def get(self, request, task_id):
        '''GET the detail view of a single task on the todo list'''
        task = Task.objects.get(id=task_id)
        form = TaskForm(initial={'description': task.description})
        return render(
            request=request, template_name='detail.html', context={'form':form, 'id': task_id}
        )

    def post(self, request, task_id):
        '''Update or delete the specific task based on what the user submitted in the form'''
        task = Task.objects.filter(id=task_id)
        if 'save' in request.POST:
            form = TaskForm(request.POST)
            if form.is_valid():
                task_description = form.cleaned_data['description']
                task.update(description=task_description)
        elif 'delete' in request.POST:
            task.delete()
        elif 'complete' in request.POST:
            task.update(completed=True)

        # "redirect" to the todo homepage
        return redirect('todo_list')

class NoteListView(View):
    def get(self, request):
        "'GET the note list homepage, listing all notes in the order that they were created'"
        notes = Note.objects.all().order_by('-id')
        form = NoteForm()

        return render(
            request=request, template_name='notes.html', context={'notes': notes, 'form': form}
        )
    def post(self, request):
        "'POST the data in the form submitted by the user, creating a new task in the todo list'"
        form=NoteForm(request.POST)
        if form.is_valid():
            note_text = form.cleaned_data['description']
            print(note_text)
            Note.objects.create(text=note_text)
            # note=Note.objects.create(text=note_description)
            # note.save()

        # "redirect" to the todo homepage
        return redirect('todo_list')


# class NoteDetailView(View):
#     def get(self, request, note_id):
#         "'GET the detail view of a single note on the note list'"
#         note = Note.objects.get(id=note_id)
#         note_form = NoteForm(instance=note)
#         return render(
#             request=request, template_name='detail.html', context={'note_form': note_form, 'note_id': note_id}
#         )

#     def post(self, request, note_id):
#         "'Update or delete the specific task based on what the user submitted in the form'"
#         note = Note.objects.get(id=note_id)

#         if 'save' in request.POST:
#             form = NoteForm(request.POST, instance=note)
#             form.save()
#             # "redirect" to the todo homepage
#         return redirect('todo_list')

todo_files/templates/detail.html
<form action="{% url 'task' id %}" method="POST">
    {% csrf_token %}
    {{ form }}
    <input type="submit" name="save" value="Save" />
    <input type="submit" name="delete" value="Delete" />
    <input type="submit" name="complete" value="Mark Complete" />
</form>

todo_files/templates/list.html
<h1>Tasks</h1>



<h2>To Do:</h2>

<ul>
    {% for task in tasks %}
        {% if task.completed == False%}
            <li><a href="{% url 'task' task.id %}">{{ task.description }}</a></li> 
        {% endif %}
    {% endfor %}
</ul>

<form action="{% url 'todo_list' %}" method="POST">
    {% csrf_token %}
    {{ form }}
    <input type="submit" name="create" value="Create" />
</form>

<h2>Completed Tasks:</h2>

<ul>
    {% for task in tasks %} 
        {% if task.completed == True %}
    <li><a href="{% url 'task' task.id %}">{{ task.description }}</a></li>
        {% endif %}
    {% endfor %}
</ul>

<!-- <h2>Notes to Self:</h2>

<form action="{% url 'note_list' %}" method="Post">
{% csrf_token %} 
{{ form2 }}
<input type="submit" name="create" value="Create" />
</form>

<ol>
    {% for note in notes %} 
      <li><a href="{% url 'note' note.id %}">{{ note.text }}</a></li>
     {% endfor %}
</ol>  -->

<a href="{% url 'note' %}">(Click Here To Go To Notes Page)</a>

todo_files/templates/notes.html
<!-- <form action="{% url 'note' id %}" method="POST">
    {% csrf_token %}
    {{ form }}
    <input type="submit" name="save" value="Save" />
    <input type="submit" name="delete" value="Delete" />
    
</form> -->

<h1>Notes to Self</h1> 

<ol>
    {% for note in notes %} 
        <li> {{ note.text }} </li> 
    {% endfor %} 
</ol> 

<form action="{% url 'note' %}" method="POST">
    {% csrf_token %} 
    {{ form }} 
    <input type="submit" name="create" value="Create"/>
</form>

<a href="{% url 'todo_list' %} ">Return Home
</a>